In [1]:
import pandas as pd

In [4]:
data = {
    'Name': ['Gopal',"Ram","Sham"],
    'Age' : [22,21,22],
    'City' : ["Tandur","Unknown","Unknown"] 
}


df = pd.DataFrame(data)

print(df)

    Name  Age     City
0  Gopal   22   Tandur
1    Ram   21  Unknown
2   Sham   22  Unknown

In [5]:
df['Salary'] = [0,'NULL','NULL']

df

    Name  Age     City Salary
0  Gopal   22   Tandur      0
1    Ram   21  Unknown   NULL
2   Sham   22  Unknown   NULL

In [8]:
data_2 = [
    {'Name' : 'Gopal','Age' : 22},
    {'Name' : "Shyam",'Age' : 'Unknown'}
]

# df2

# for record in data_2:
#     record['Salary'] = 1000

df2 = pd.DataFrame(data_2)
df2['Salary'] = [0,'1000']
print(df2)

    Name      Age Salary
0  Gopal       22      0
1  Shyam  Unknown   1000

## Data Manipulation using Pandas

In [10]:
df = pd.read_csv('data.csv')

# To fetch the first and last few rows
print(df.head(5), "\n")
print(df.tail(5))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [11]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   29.000000
mean    68.437500  103.500000  128.500000  306.451724
std     70.039591    7.832933   12.998759   66.442116
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  300.000000
75%     60.000000  106.500000  132.250000  345.300000
max    450.000000  130.000000  175.000000  479.000000

In [12]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [17]:
# Hanlding Missing Values

df.isnull().any(axis = 1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22     True
23     True
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
dtype: bool